/* Tra cứu danh mục BVTV: chạy cục bộ, không phụ thuộc thư viện ngoài. */
(function boot(){
  if(!Array.isArray(window.BVTV_PRODUCTS)){
    const source=document.createElement('script');source.src='dmbvtv-data.js';source.onload=boot;source.onerror=()=>{const el=document.getElementById('lookup-status');if(el)el.textContent='Không thể nạp dữ liệu danh mục BVTV.'};document.head.appendChild(source);return;
  }
  const products=window.BVTV_PRODUCTS,byId=id=>document.getElementById(id);
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const normalize=value=>String(value??'').normalize('NFC').toLocaleLowerCase('vi').trim();
  const searchRow=document.querySelector('.lookup-search-row'),options=document.querySelector('.lookup-options');
  const multiStyle=document.createElement('style');multiStyle.textContent='.lookup-heading h1{max-width:1000px;color:#111;font-size:clamp(38px,4.5vw,58px);letter-spacing:.01em}.lookup-heading>div>p:last-child{color:#26352c;font-size:14px}.lookup-search-row.lookup-search-multi{grid-template-columns:repeat(5,minmax(0,1fr));align-items:start}.lookup-search-row label>span{color:#18281e;font-size:10px}.lookup-search-row input{color:#111;font-size:13px}.lookup-search-multi label small{display:block;min-height:29px;margin-top:7px;color:#4e5d54;font-size:10px;line-height:1.4}.lookup-guide{color:#26372d;font-size:11px;line-height:1.55}.lookup-guide code{color:#0d4228;font-weight:900}.lookup-options{justify-content:space-between}.lookup-options .lookup-clear-button{display:inline-flex;align-items:center;justify-content:center;gap:7px;flex:0 0 auto;min-width:108px;font-size:10px;letter-spacing:.05em}.reset-icon{display:grid;place-items:center;width:20px;height:20px;border-radius:50%;background:#e4f1dc;color:#174d32;font-size:14px;line-height:1}.lookup-clear-button:hover .reset-icon{background:#174d32;color:#fff}.results-head #lookup-status,.lookup-table td{color:#26372d;font-size:12px}.lookup-table th{color:#173b27;font-size:10px}.company-result{padding:0;border:0;background:transparent;color:#155b34;font:inherit;font-weight:900;text-align:left;text-decoration:underline;text-underline-offset:3px;cursor:pointer}@media(max-width:1000px) and (min-width:721px){.lookup-search-row.lookup-search-multi{grid-template-columns:repeat(3,1fr)}}@media(max-width:720px){.lookup-heading h1{font-size:36px}.lookup-search-row.lookup-search-multi{grid-template-columns:1fr}.lookup-options{align-items:stretch}.lookup-options .lookup-clear-button{width:100%}}';document.head.appendChild(multiStyle);
  const readableStyle=document.createElement('style');readableStyle.textContent='.lookup-heading h1{max-width:none;font-size:clamp(30px,3.5vw,44px)}.lookup-heading>div>p:last-child{max-width:none;font-size:16px;white-space:nowrap}.lookup-search-row label>span{font-size:12px}.lookup-search-row input{font-size:15px}.lookup-search-multi label small{font-size:12px}.lookup-guide{font-size:13px}.results-kicker{font-size:12px}.results-head #lookup-status{font-size:13px}.lookup-table{table-layout:fixed;min-width:1050px}.lookup-table th{font-size:12px}.lookup-table td{font-size:14px;overflow-wrap:anywhere}.lookup-table th:nth-child(1),.lookup-table td:nth-child(1){width:15%}.lookup-table th:nth-child(2),.lookup-table td:nth-child(2){width:14%}.lookup-table th:nth-child(3),.lookup-table td:nth-child(3){width:34%}.lookup-table th:nth-child(4),.lookup-table td:nth-child(4){width:22%}.lookup-table th:nth-child(5),.lookup-table td:nth-child(5){width:15%}@media(max-width:720px){.lookup-heading h1{font-size:30px}.lookup-heading>div>p:last-child{white-space:normal}.lookup-table{min-width:0;table-layout:auto}.lookup-table td{font-size:14px}.lookup-table th:nth-child(n),.lookup-table td:nth-child(n){width:auto}}';document.head.appendChild(readableStyle);
  const resetStyle=document.createElement('style');resetStyle.textContent='.lookup-options .lookup-clear-button{border-color:#174d32;background:#174d32;color:#fff}.lookup-options .lookup-clear-button .reset-icon{background:rgba(255,255,255,.16);color:#fff}.lookup-options .lookup-clear-button:hover{border-color:#0c3823;background:#0c3823;color:#fff}.lookup-options .lookup-clear-button:hover .reset-icon{background:rgba(255,255,255,.24);color:#fff}';document.head.appendChild(resetStyle);
  const centeredHeadingStyle=document.createElement('style');centeredHeadingStyle.textContent='.lookup-heading{display:block;text-align:center}.lookup-heading>div{width:100%}.lookup-heading .page-kicker{font-size:12px}.lookup-heading h1{margin-left:auto;margin-right:auto}.lookup-heading>div>p:last-child{margin-left:auto;margin-right:auto;text-align:center}';document.head.appendChild(centeredHeadingStyle);
  document.querySelector('.lookup-count-label')?.remove();
  const lookupTitle=document.querySelector('.lookup-heading h1');if(lookupTitle)lookupTitle.textContent='TRA CỨU NHANH, CHỌN ĐÚNG THUỐC';
  searchRow.classList.add('lookup-search-multi');
  searchRow.innerHTML='<label><span>Tên thương phẩm</span><input id="lookup-product" type="search" placeholder="Nhập tên thuốc"><small>Ví dụ: Ababetter 5EC</small></label><label><span>Hoạt chất</span><input id="lookup-active" type="search" placeholder="Nhập hoạt chất"><small>Ví dụ: Abamectin; Emamectin</small></label><label><span>Dịch hại</span><input id="lookup-pest" type="search" placeholder="Nhập dịch hại"><small>Ví dụ: rệp, sâu xanh</small></label><label><span>Cây trồng</span><input id="lookup-crop" type="search" placeholder="Nhập cây trồng"><small>Ví dụ: xoài; cam</small></label><label><span>Công ty đăng ký</span><input id="lookup-company" type="search" placeholder="Nhập tên công ty"><small>Ví dụ: Công ty An Nông</small></label>';
  options.innerHTML='<span class="lookup-guide">Ô không nhập được hiểu là <strong>chọn tất cả</strong>. Dùng dấu <code>","</code> là <strong>hoặc</strong> (sâu xanh, rầy nghĩa là có sâu xanh hoặc có rầy), dấu <code>";"</code> là <strong>và</strong> (sâu xanh; rầy nghĩa là có sâu xanh và có rầy).</span>';
  const fieldKeys=['product','active','pest','crop','company'];
  const inputs=Object.fromEntries(fieldKeys.map(key=>[key,byId(`lookup-${key}`)]));
  const incomingParams=new URLSearchParams(window.location.search);fieldKeys.forEach(key=>{const value=incomingParams.get(key);if(value)inputs[key].value=value});
  const body=byId('lookup-table-body'),sizeSelect=byId('lookup-page-size'),status=byId('lookup-status'),pages=byId('lookup-pagination'),productDialog=byId('product-dialog'),clearButton=byId('lookup-clear-button');if(!body)return;
  clearButton.hidden=false;clearButton.innerHTML='<span class="reset-icon" aria-hidden="true">↻</span><span>ĐẶT LẠI</span>';options.appendChild(clearButton);
  const companyHeading=document.querySelector('.lookup-table thead th:last-child');if(companyHeading)companyHeading.textContent='Công ty';
  let current=1,currentResults=products,searchTimer;
  const disclaimer=document.querySelector('.lookup-disclaimer');if(disclaimer)disclaimer.innerHTML='<strong>Lưu ý:</strong> Dữ liệu được nhập từ danh mục theo Thông tư số 75/2025/TT-BNNMT. Trước khi sử dụng, hãy đối chiếu nhãn sản phẩm, tình trạng đăng ký hiện hành và hướng dẫn chuyên môn.';
  sizeSelect.innerHTML='<option value="10">10</option><option value="15" selected>15</option><option value="30">30</option><option value="50">50</option><option value="100">100</option><option value="500">500</option>';
  const dialogActions=productDialog.querySelector('.dialog-actions'),googleProduct=document.createElement('a');googleProduct.id='product-google';googleProduct.className='dialog-link';googleProduct.target='_blank';googleProduct.rel='noopener noreferrer';googleProduct.textContent='Tìm thông tin & giá bán ↗';dialogActions.prepend(googleProduct);
  const companyDialog=document.createElement('dialog');companyDialog.id='company-dialog';companyDialog.className='product-dialog company-dialog';companyDialog.innerHTML='<div class="dialog-inner"><div class="dialog-top"><div><p class="dialog-kicker">Thông tin doanh nghiệp</p><h2 id="company-title">Tên công ty</h2></div><button id="company-close" class="dialog-close" type="button" aria-label="Đóng">×</button></div><p class="company-note">Đơn vị có sản phẩm trong danh mục đăng ký lưu hành thuốc BVTV.</p><div class="company-actions"><a id="company-website" target="_blank" rel="noopener noreferrer">⌕ Tìm website chính thức</a><a id="company-tax" target="_blank" rel="noopener noreferrer">▦ Tra cứu mã số thuế và địa chỉ</a><button id="company-filter" type="button">⌕ Lọc thuốc của công ty này</button></div></div>';document.body.appendChild(companyDialog);
  function criteria(){return fieldKeys.flatMap(field=>inputs[field].value.split(';').map(group=>group.split(',').map(normalize).filter(Boolean)).filter(alternatives=>alternatives.length).map(alternatives=>({field,alternatives})))}
  function matching(){const filters=criteria();return filters.length?products.filter(product=>filters.every(({field,alternatives})=>alternatives.some(query=>normalize(product[field]).includes(query)))):products}
  function highlight(value){const terms=criteria().flatMap(item=>item.alternatives);let safe=escapeHtml(value);if(!terms.length)return safe;const pattern=terms.map(term=>escapeHtml(term).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');return safe.replace(new RegExp(`(${pattern})`,'giu'),'<mark>$1</mark>')}
  function quick(value,field,label){return `<button class="quick-filter" type="button" data-field="${field}" data-value="${escapeHtml(value)}" title="Lọc theo ${label}">${highlight(value)}</button>`}
  function row(product,index){return `<tr tabindex="0" data-index="${index}" aria-label="Xem chi tiết ${escapeHtml(product.product)}"><td><button class="product-name product-open" type="button">${highlight(product.product)}</button><small>${highlight(product.category)}</small></td><td>${quick(product.active,'active','hoạt chất')}</td><td>${quick(product.pest,'pest','dịch hại')}</td><td>${quick(product.crop,'crop','cây trồng')}</td><td><button class="company-result" type="button" data-company="${escapeHtml(product.company)}">${highlight(product.company)}</button></td></tr>`}
  function pagination(totalPages){const first=Math.max(1,Math.min(current-2,totalPages-4)),numbers=Array.from({length:Math.min(5,totalPages)},(_,i)=>first+i);return `<button type="button" data-page="prev" ${current===1?'disabled':''}>‹</button>${first>1?'<span>…</span>':''}${numbers.map(page=>`<button type="button" data-page="${page}" class="${current===page?'active':''}">${page}</button>`).join('')}${numbers.at(-1)<totalPages?'<span>…</span>':''}<button type="button" data-page="next" ${current===totalPages?'disabled':''}>›</button>`}
  function render(){currentResults=matching();const size=Number(sizeSelect.value),totalPages=Math.max(1,Math.ceil(currentResults.length/size));current=Math.min(current,totalPages);const start=(current-1)*size,visible=currentResults.slice(start,start+size);body.innerHTML=visible.length?visible.map(product=>row(product,products.indexOf(product))).join(''):'<tr><td class="empty-lookup" colspan="5">Không tìm thấy dữ liệu phù hợp. Hãy thử điều kiện khác.</td></tr>';status.innerHTML=currentResults.length?`Hiển thị <strong>${start+1}–${Math.min(start+size,currentResults.length)}</strong> trong <strong>${currentResults.length.toLocaleString('vi-VN')}</strong> sản phẩm.`:'Không có bản ghi phù hợp.';pages.innerHTML=pagination(totalPages);bindRows();pages.querySelectorAll('button').forEach(button=>button.onclick=()=>{const value=button.dataset.page;current=value==='prev'?current-1:value==='next'?current+1:Number(value);render()})}
  function bindRows(){body.querySelectorAll('tr[data-index]').forEach(tr=>{const product=products[Number(tr.dataset.index)],open=()=>showProduct(product);tr.querySelectorAll('.product-open').forEach(button=>button.onclick=event=>{event.stopPropagation();open()});tr.onclick=event=>{if(!event.target.closest('button'))open()};tr.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&event.target===tr){event.preventDefault();open()}};tr.querySelectorAll('.quick-filter').forEach(button=>button.onclick=event=>{event.stopPropagation();inputs[button.dataset.field].value=button.dataset.value;search();inputs[button.dataset.field].focus()});tr.querySelector('.company-result').onclick=event=>{event.stopPropagation();showCompany(product.company)}})}
  function showProduct(product){byId('dialog-title').textContent=product.product;byId('dialog-details').innerHTML=`<dt>Hoạt chất</dt><dd>${escapeHtml(product.active)}</dd><dt>Phân loại</dt><dd>${escapeHtml(product.category)}</dd><dt>Đặc trị</dt><dd>${escapeHtml(product.pest)}</dd><dt>Cây trồng</dt><dd>${escapeHtml(product.crop)}</dd><dt>Công ty ĐK</dt><dd>${escapeHtml(product.company)}</dd>`;googleProduct.href=`https://www.google.com/search?q=${encodeURIComponent('Thuốc BVTV '+product.product)}`;productDialog.showModal?productDialog.showModal():productDialog.setAttribute('open','')}
  function showCompany(company){byId('company-title').textContent=company;byId('company-website').href=`https://www.google.com/search?q=${encodeURIComponent('website chính thức '+company)}`;byId('company-tax').href=`https://masothue.com/Search/?q=${encodeURIComponent(company)}`;byId('company-filter').dataset.company=company;companyDialog.showModal?companyDialog.showModal():companyDialog.setAttribute('open','')}
  function search(){current=1;render()}function clear(){fieldKeys.forEach(key=>inputs[key].value='');search();inputs.pest.focus()}
  clearButton.onclick=clear;Object.values(inputs).forEach(input=>{input.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,250)};input.onkeydown=event=>{if(event.key==='Enter'){clearTimeout(searchTimer);search()}}});sizeSelect.onchange=search;
  ['dialog-close','dialog-done'].forEach(id=>byId(id).onclick=()=>productDialog.close());productDialog.onclick=event=>{if(event.target===productDialog)productDialog.close()};byId('company-close').onclick=()=>companyDialog.close();companyDialog.onclick=event=>{if(event.target===companyDialog)companyDialog.close()};byId('company-filter').onclick=event=>{inputs.company.value=event.currentTarget.dataset.company;companyDialog.close();search()};render();
}());
