/* Trình phát và thư viện video nông nghiệp từ kênh @banmoinha. */
(()=>{'use strict';
const raw=[['D6Bjf8QSJEM','Vườn mai Bình Lợi sau Tết chờ xả tàn','Mùa vụ','Cây mai · Sau Tết'],['yVUIfX0sa20','Cách chăm sóc cây mai sau Tết','Kỹ thuật','Cây mai · Phục hồi'],['Vlj_eonUtvg','Kinh nghiệm chăm sóc để đào ra hoa đúng dịp Tết','Mùa vụ','Cây đào · Ra hoa'],['7-GHia0DT9o','11 loại lan khó trồng','Kỹ thuật','Hoa lan'],['Ye8p86BK2J4','Kỹ thuật ghép bơ','Kỹ thuật','Cây bơ · Nhân giống'],['jVzIZ76a1Fg','Kỹ thuật ghép bưởi','Kỹ thuật','Cây có múi · Nhân giống'],['n8ZGp5BeqQ0','Ứng dụng nhà màng và hệ thống tưới nhỏ giọt','Kỹ thuật','Nông nghiệp công nghệ cao'],['EC1OB8rX0KQ','Kỹ thuật và phương pháp trồng cà phê','Kỹ thuật','Cà phê · Thiết lập vườn'],['8zvyKorr9SM','Bí quyết trồng hoa cúc','Kỹ thuật','Hoa cúc'],['B8fjzUoU9wU','Mô hình trồng dưa trong nhà lưới','Kỹ thuật','Cây dưa · Mô hình thực tế'],['IVOT8ChJKdI','Nhà màng trồng rau thủy canh cho miền Tây Nam Bộ','Kỹ thuật','Rau màu · Nhà màng'],['mvur5sB_39Y','Hướng dẫn xây dựng nhà kính màng nilon trồng rau','Kỹ thuật','Rau màu · Cơ sở canh tác'],['JbFM18sIcOA','Giảm thất thoát khi thu hoạch và sau thu hoạch lúa','Mùa vụ','Lúa · Thu hoạch'],['M-xzybmiCg4','Sáng bông chắc hạt','Mùa vụ','Lúa · Làm hạt'],['ON4C3KO8Psg','Lúa khỏe – trúng mùa','Mùa vụ','Lúa · Kinh nghiệm mùa vụ']];
const videos=raw.map(([youtubeId,title,category,meta],index)=>({id:index+1,youtubeId,title,category,meta,channel:'Bảo vệ cây trồng'}));const $=id=>document.getElementById(id),E={player:$('player'),placeholder:$('placeholder'),title:$('current-title'),channel:$('current-channel'),meta:$('current-meta'),desc:$('current-description'),youtube:$('youtube-button'),related:$('related-list'),relatedTitle:$('related-title'),relatedCount:$('related-count'),grid:$('video-grid'),count:$('result-count'),empty:$('empty-state'),search:$('video-search'),sort:$('video-sort'),panel:$('search-panel')};let active=null,tab='all',rate=1;
const thumb=v=>`https://i.ytimg.com/vi/${v.youtubeId}/hqdefault.jpg`,watch=v=>`https://www.youtube.com/watch?v=${v.youtubeId}`,embed=v=>`https://www.youtube-nocookie.com/embed/${v.youtubeId}?autoplay=1&rel=0&playsinline=1&enablejsapi=1&origin=${encodeURIComponent(location.origin)}`,norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function applyRate(){E.player.contentWindow?.postMessage(JSON.stringify({event:'command',func:'setPlaybackRate',args:[rate]}),'*')}
function setRate(value){rate=Math.max(.25,Math.min(2,Math.round(value*20)/20));document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===rate));$('speed-range').value=rate;$('speed-value').textContent=rate.toFixed(2).replace('.',',')+'×';applyRate()}
	let volume=100,muted=false;function setVolume(value){volume=Math.max(0,Math.min(100,Math.round(value)));$('volume-range').value=volume;$('volume-value').textContent=`${volume}%`;E.player.contentWindow?.postMessage(JSON.stringify({event:'command',func:'setVolume',args:[volume]}),'*');if(volume>0&&!muted){E.player.contentWindow?.postMessage(JSON.stringify({event:'command',func:'unMute',args:[]}),'*')}}function toggleMute(){muted=!muted;E.player.contentWindow?.postMessage(JSON.stringify({event:'command',func:muted?'mute':'unMute',args:[]}),'*');$('volume-toggle').textContent=muted?'🔇 Bật âm thanh':'🔊 Âm thanh';$('volume-toggle').setAttribute('aria-label',muted?'Bật âm thanh':'Tắt âm thanh')}
function play(v){active=v;E.placeholder.hidden=true;E.player.src=embed(v);E.player.title=v.title;E.title.textContent=v.title;E.channel.textContent='Bảo vệ cây trồng';E.meta.innerHTML=`<span>${v.category}</span><span>${v.meta}</span>`;E.desc.textContent=`${v.title}. Video được phát trực tiếp từ kênh YouTube Bảo vệ cây trồng.`;E.youtube.href=watch(v);E.youtube.classList.remove('disabled');render();renderRelated(v);document.documentElement.scrollTop=0;document.body.scrollTop=0;window.scrollTo(0,0);setTimeout(()=>{document.documentElement.scrollTop=0;document.body.scrollTop=0;window.scrollTo(0,0)},80);setTimeout(applyRate,900)}
function list(){let data=videos.filter(v=>tab==='all'||tab==='playlist'||v.category===tab);const q=norm(E.search.value.trim());if(q)data=data.filter(v=>norm(`${v.title} ${v.meta} ${v.category}`).includes(q));if(E.sort.value==='az')data.sort((a,b)=>a.title.localeCompare(b.title,'vi'));if(E.sort.value==='za')data.sort((a,b)=>b.title.localeCompare(a.title,'vi'));return data}
function card(v,playlist=false){return `<article class="video-card ${playlist?'playlist-card':''} ${active===v?'active':''}" role="button" tabindex="0" data-id="${v.id}"><div class="video-thumb"><img src="${thumb(v)}" alt="${v.title}" loading="lazy"><div class="video-overlay"><span>▶</span></div></div><h3>${playlist?v.category:v.title}</h3><p>${playlist?'Xem nhóm video':v.meta}</p></article>`}
function render(){const data=list();let html;if(tab==='playlist'){const groups=[...new Set(data.map(v=>v.category))];html=groups.map(group=>card(data.find(v=>v.category===group),true)).join('');E.count.textContent=`${groups.length} danh sách phát`}else{html=data.map(v=>card(v)).join('');E.count.textContent=`${data.length} video`}E.grid.innerHTML=html;E.empty.hidden=!!html;E.grid.querySelectorAll('[data-id]').forEach(el=>{const v=videos.find(x=>x.id===Number(el.dataset.id));el.onclick=()=>play(v);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play(v)}}})}
function renderRelated(v){const data=(v?videos.filter(x=>x.category===v.category):videos).slice(0,10);E.relatedTitle.textContent=v?v.category:'Clip mới nhất';E.relatedCount.textContent=`${data.length} clip`;E.related.innerHTML=data.map(x=>`<article class="related-card ${active===x?'active':''}" role="button" tabindex="0" data-id="${x.id}"><div class="related-thumb"><img src="${thumb(x)}" alt="${x.title}" loading="lazy"></div><div class="related-info"><h3>${x.title}</h3><p>${x.meta}</p></div></article>`).join('');E.related.querySelectorAll('[data-id]').forEach(el=>{const x=videos.find(v=>v.id===Number(el.dataset.id));el.onclick=()=>play(x);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play(x)}}})}
document.querySelectorAll('#video-tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#video-tabs button').forEach(x=>x.classList.toggle('active',x===b));render()});$('search-toggle').onclick=()=>{E.panel.hidden=!E.panel.hidden;if(!E.panel.hidden)E.search.focus()};$('search-clear').onclick=()=>{E.search.value='';render();E.search.focus()};E.search.oninput=render;E.sort.onchange=render;$('reset-filter').onclick=()=>{tab='all';E.search.value='';E.sort.value='default';document.querySelectorAll('#video-tabs button').forEach((b,i)=>b.classList.toggle('active',i===0));render()};document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>setRate(Number(b.dataset.speed)));$('speed-range').oninput=e=>setRate(Number(e.target.value));$('speed-down').onclick=()=>setRate(rate-.05);$('speed-up').onclick=()=>setRate(rate+.05);$('volume-range').oninput=e=>{muted=false;$('volume-toggle').textContent='🔊 Âm thanh';$('volume-toggle').setAttribute('aria-label','Tắt âm thanh');setVolume(e.target.value)};$('volume-toggle').onclick=toggleMute;E.player.onload=()=>setTimeout(()=>{applyRate();setVolume(volume)},700);render();renderRelated();const requestedVideo=new URLSearchParams(location.search).get('video');const initialVideo=videos.find(v=>v.youtubeId===requestedVideo);if(initialVideo)play(initialVideo);
})();
